### ISSUE TITLE
Log unsuccessful DAPS connection

### ISSUE THREAD

**Issue by juliapampus** [International-Data-Spaces-Association/IDS-Connector-Framework#9]
When setting the connector to `PRODUCTIVE_DEPLOYMENT` and the DAPS has not been reached due to e.g. proxy settings, it retreives a rejection message from the responding connector (DSC) caused by a missing DAT: `Token cannot be null`. Maybe it would be helpful to somehow log that the identification process has failed at the connector's start, so the user knows that this has to be fixed before sending requests?

**Comment by tmberthold** [comment]
Will be implemented with the next major release, for this an exception handling will be built in, so that no messages can be sent without a valid DAPS DAT anymore, unless the connector is in the test_deployment.

**Comment by tmberthold** [comment]
If an error occurs while fetching a DAPS DAT, an exception is returned to the connector developer instead of just logging this error and sending an IDS message with invalid DAT entry. The message for which a DAT should be organized is no longer sent as a result.

Exception structure: 

![image](https://user-images.githubusercontent.com/75306992/107226827-ea728600-6a1a-11eb-81f8-5d20e73c4d00.png)


Is implemented on the branch for the new major version 5.0.0.:
https://github.com/FraunhoferISST/IDS-Connector-Framework/commit/d7ff580e13c54688876c0cec9d313cdaafa3700d
